### ISSUE TITLE
Feature Request: Make the extension aware of Magento's extension attributes

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/phpstan-magento#112]
Come up with a plan to make the PHPStan extension aware of defined [extension attributes](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/attributes.html#extension).

**Comment by mattwellss** [comment]
Hey there! Love the extension. I took a stab at handling extension attribute interface autoloading

https://gist.github.com/mattwellss/5b133af5cf69793d0953d5fa0087e6ea

My approach is not merge-ready, though...

1. When the `DirectoryList` is initialized, I'm providing `'.'` as the path, which is only correct when running phpstan from the project root.
2. It only handles `ThingExtensionInterface`. This might be no problem, since `$thingInstance->getExtensionAttributes()` is generally documented to return the interface rather than the class.
3. It adds dependencies on `laminas/laminas-code` and `symfony/finder`. Both of these are required by Magento, so they should be present, but I can understand wanting to find alternatives

Let me know what you think.

**Comment by shochdoerfer** [comment]
Awesome! Thanks for the kind word and thanks for starting to work on this.

Your approach is a bit different from what I had in mind but contains a few interesting bits that we may be able to re-use.

I think we need to have a bit more flexibility where the xml files are located since we have users that use our module for developing "just" a single module but also for developing a complete Magento project. Having seen all so many different directory layouts for Magento applications, I feel we can't define just one standard or recursively search through all existing directories as this would slow down the parsing. My original idea was to let the user define a list of paths where to look for the xml files, e.g. the location of the app/code directory and the location of the vendor directory. The [PHPStan Symfony plugin](https://github.com/phpstan/phpstan-symfony/) does it in a similar fashion by letting the users define a [path to the XML configuration](https://github.com/phpstan/phpstan-symfony/blob/master/extension.neon).

I don't think we would actually need an additional autoloader. Ideally, we could get rid of it as this is a really hacky solution. I'd rather like to see an implementation of the `PHPStan\Reflection\MethodsClassReflectionExtension` similar to [AbstractMagicMethodReflectionExtension](https://github.com/bitExpert/phpstan-magento/blob/master/src/bitExpert/PHPStan/Magento/Reflection/AbstractMagicMethodReflectionExtension.php) and it's subclass [DataObjectMagicMethodReflectionExtension](https://github.com/bitExpert/phpstan-magento/blob/master/src/bitExpert/PHPStan/Magento/Reflection/Framework/DataObjectMagicMethodReflectionExtension.php). In the hasMethod() implementation we would need to check if the class in question contains the requested extension attribute. In the getMethod() implemenation we would return the `PHPStan\Reflection\MethodReflection` for the requested get/set method for the extension attribute.

If we go that route we should also figure out how to properly cache things so that we do not have to parse the xml files for each phpstan run. Maybe storing the information we need (name, type) in a JSON file for each found xml file to make sure file time expiry detection will properly work.

Looking forward to your feedback!

**Comment by mattwellss** [comment]
> I think we need to have a bit more flexibility where the xml files are located since we have users that use our module for developing "just" a single module but also for developing a complete Magento project. Having seen all so many different directory layouts for Magento applications, I feel we can't define just one standard or recursively search through all existing directories as this would slow down the parsing

Great point! It's important to stay in the right mindset when I'm working on something that will be used in very different ways.

That said, I believe the existing logic does find every extension attribute relatively efficiently. With the most recent changes, the Finder looks for `extension_attributes.xml` files in each enabled/registered module's `etc` directory. This approach eliminates recursive search and finds declared extension attributes, wherever they might be.

My lack of experience may be showing, but I believe the developer experience is best when we avoid making users specify the paths to each extension attributes file. In my own case, that means specifying 43 paths.

Performance-wise, the current version adds about 100ms when checking a single files with phpstan (uncached). It's processing about 450 modules and 43 extension attributes configurations. This particular test case generates two extension attribute interfaces. Once the extension attributes are generated, the loader doesn't have an identifiable performance impact (as expected). 

In a larger test (an entire module), I can't see a difference in performance when running uncached.

One lingering issue: when another extension attribute is added, there's no way to invalidate the cached class. It's not a problem for proxies and factories (which I copied), but extension attributes need more attention.

**Comment by shochdoerfer** [comment]
My bad for not responding earlier. Had to focus on some other things and then lost track of this issue.

Basically, we have to cover 4 use-cases:
 - module development
   - having PHPStan & our extension installed in the root composer.json of the module
   - having PHPStan & our extension installed elsewhere
 - Magento application development
    - having PHPStan & our extension installed in the root composer.json of the module
   - having PHPStan & our extension installed elsewhere

In my initial idea, I was thinking to find the respective XML files for the extension attributes recursively without relying on Magento's internal logic. Seeing your approach it feels like it makes more sense. I am just not sure if it works when you develop a module in isolation as the standard Magento configuration files would be lacking. That should be the first thing we have to test. I am fine to re-use existing Magento logic when we can, especially if that means we can ignore some additional caching in our extension :)

Anything else I could be of help to guide you to start working on the PR?

**Comment by mattwellss** [comment]
Excellent! I'm really busy for the next month or so, but I'll have time to focus on this once that's over with.

When I come back I'll follow whatever strategy (autoloading or reflection) is in use for factories/proxies, if that's OK.

**Comment by mattwellss** [comment]
OK, after a long delay I got back into this on Friday. My current challenge is ensuring phpstan can find the appropriate extension attribute interface.

Here's a summary of my explorations:

First I tried building a `phpstan.broker.dynamicMethodReturnTypeExtension` which "generates" an empty interface with eval. Subsequent calls to extension attributes interface instances are handled by a `phpstan.broker.methodsClassReflectionExtension`. That method _can_ work, but I'd really like to avoid eval, which is why I looked into other paths

Next I tried implementing a custom `PHPStan\Type\Type`, which eliminates the need to have an actual interface. This seemed pretty neat until I checked some code that used a phpdoc annotation. The annotation prompts PHPStan to look for the interface, which doesn't exist and breaks its ability to analyse. Because of that limitation, I've basically tossed away this solution.

While eval isn't ideal, the first option still offers improvements over my earlier attempt, specifically as caching is concerned (newly introduced attributes don't require deleting the cache!). But before I move forward, I'm curious about your thoughts.

**Comment by shochdoerfer** [comment]
The `phpstan.broker.dynamicMethodReturnTypeExtension` feels right to me, similar to what we have done for the [ObjectManagerDynamicReturnTypeExtension.](https://github.com/bitExpert/phpstan-magento/blob/master/src/bitExpert/PHPStan/Magento/Type/ObjectManagerDynamicReturnTypeExtension.php):
 - in the getClass() method you return the the `ExtensibleDataInterface` interface name (not sure if that works or if PHPStan does expect a class name to be returned)
 - in the isMethodSupported() method you would check if the `getExtensionAttributes()` method was called
 - in the getTypeFromMethodCall() method you would return the array of extension attributes with the PHPStan type system, see [here](https://github.com/bitExpert/phpstan-magento/blob/master/src/bitExpert/PHPStan/Magento/Type/TestFrameworkObjectManagerDynamicReturnTypeExtension.php#L110). There's an implementation `ConstantArrayType` which allows to check vor valid keys in the array which would be a cool to have.

Does that help? I may have missed something, the PHPStan logic is quite complex but I feel this could work.

**Comment by mattwellss** [comment]
That's similar to my second implementation (though I built a class), and the issue of the actual interface being nonexistent remains, as far as I know. When I use my own non-interface-generating solution, I get this from PHPStan:
```
  447    PHPDoc tag @var for variable $orderExtension contains unknown class    
         Magento\Sales\Api\Data\OrderExtensionInterface.                        
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols     
```

I know it's not necessary to use a PHPDoc when the function itself properly documents its own return type, but it seems like something we ought to support. (And also, when we look to the future when Factories/Proxies will be handled in a similar way the issue becomes more pressing, since those classes are often used in constructor arguments)

**Comment by mattwellss** [comment]
Definitely. It's past time I integrated my WIP changes into a fork anyway. Stand by while I get something ready 😄

**Comment by shochdoerfer** [comment]
No worries, take the time you need. I am quite busy the next few weeks but I'll try my very best to support you so that we can get feature in soon. I know a few people eagerly waiting for this (no pressure!) :)

**Comment by shochdoerfer** [comment]
@mattwellss how are you progressing on this? Any help needed?

**Comment by mattwellss** [comment]
Sorry that I haven't followed up. Ran out of my "20%" time at work, but that's starting again soon. I've integrated the autoloader version (which generates a file in PHPStan's tmp directory) into our codebase already, and it's working great. At the very least I'll make sure to get those changes pushed to our fork (https://github.com/lacrossefootwear/phpstan-magento).

I still plan to switch away from that strategy to what we've discussed, but I got stuck in some metaphorical weeds. I'll also get that branch published once it exists.

**Comment by shochdoerfer** [comment]
Good to hear & good to know that things are working fine in your fork. I might start experimenting with my approach in the next few weeks, will let you know here about the results maybe we both can drive this forward.

**Comment by sprankhub** [comment]
I was about to create an issue and found this existing one :) We stumbled upon this while using:

* `Magento\InventoryApi\Api\Data\SourceInterface::getExtensionAttributes`
* `Magento\InventoryApi\Api\Data\SourceExtension` / `Magento\InventoryApi\Api\Data\SourceExtensionInterface`
* `Magento\InventoryApi\Api\Data\SourceExtensionInterfaceFactory`

Pretty sure your implementation will handle this, but maybe it is interesting seeing a real-world core use case anyway :)

Thanks!

**Comment by mattwellss** [comment]
@sprankhub I've gotten a lot from that page in the past, thanks for linking to it!

I'm back on this as of a couple days ago! Working on the "dynamic method return type extension" version. With `checkNullables` and `checkUnionTypes` turned on in the phpstan configuration file, code like this triggers warnings:
```php
foreach ($itemsToUpdate as $itemToUpdate) {
    /** @var \Magento\Sales\Api\Data\OrderItemInterface $itemToUpdate */
    $extension = $itemToUpdate->getExtensionAttributes();
    $shipDates = $extension->getShipDates();
    $shipDate = $this->shipDateFactory->create();
    $shipDate->setShipDate(new \DateTime($stockAvailabilityDate));
    $shipDates[] = $shipDate;
    $extension->setShipDates($shipDates);
    $itemToUpdate->setExtensionAttributes($extension);
}
```

In this case, `ship_dates` is a custom extension attribute in our shop. The phpstan output looks like this (level 5, with the two aforementioned additional checks enabled):
```
 ------ --------------------------------------------------------------------- 
  Line   ToOrderItem.php                                                      
 ------ --------------------------------------------------------------------- 
  43     Cannot call method getShipDates() on                                 
         Magento\Sales\Api\Data\OrderItemExtensionInterface|null.             
  47     Cannot call method setShipDates() on                                 
         Magento\Sales\Api\Data\OrderItemExtensionInterface|null.             
  48     Parameter #1 $extensionAttributes of method                          
         Magento\Sales\Api\Data\OrderItemInterface::setExtensionAttributes()  
         expects Magento\Sales\Api\Data\OrderItemExtensionInterface,          
         Magento\Sales\Api\Data\OrderItemExtensionInterface|null given.       
 ------ --------------------------------------------------------------------- 
```

This looks pretty great so far! I've built a `DynamicMethodReturnTypeExtension` that returns a new class extending `ObjectType`. In order to avoid "unknown class" errors, I return `\Magento\Framework\Api\ExtensionAttributesInterface` as the return value of `getClassName`, but use the real interface name otherwise. 

This approach fails when the real extension attributes interface name is specified in a `@var` tag:
```php
foreach ($itemsToUpdate as $itemToUpdate) {
    /** @var OrderItemExtensionInterface|null $extension */
    $extension = $itemToUpdate->getExtensionAttributes();
    $shipDates = $extension->getShipDates();
    $shipDate = $this->shipDateFactory->create();
    $shipDate->setShipDate(new \DateTime($stockAvailabilityDate));
    $shipDates[] = $shipDate;
    $extension->setShipDates($shipDates);
    $itemToUpdate->setExtensionAttributes($extension);
}
```

Here's (part of) the PHPStan result:

```
 ------ --------------------------------------------------------------------- 
  Line   ToOrderItem.php                                                      
 ------ --------------------------------------------------------------------- 
  43     PHPDoc tag @var for variable $extension contains unknown class       
         Magento\Sales\Api\Data\OrderItemExtensionInterface.                  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols   
```

I believe we'll still have to implement an autoloader (or something similar, like aliases) in order to prevent this.

@shochdoerfer what do you think?

**Comment by shochdoerfer** [comment]
@mattwellss thanks for picking things up again! I was not aware of the class generation in the background, I somehow had "just" the XML config in mind. So yes, if Magento generates classes, we need to generate them also and use a custom autoloader to load them so that PHPStan is properly aware of them.

**Comment by shochdoerfer** [comment]
@sprankhub thanks for sharing the link, that makes things a lot clearer to me. Looks like after all those years I still underestimate the Magento magic happening in the background :P

**Comment by mattwellss** [comment]
Cool, in that case I can clean up my extension attributes autoloading code that's already in use. Unless something goes awry at work I should be able to open a PR next week!

**Comment by mattwellss** [comment]
Here's a start! A lot of clean up is warranted (I had to prevent verification steps on both commit and push 🙊)

https://github.com/bitExpert/phpstan-magento/compare/master...lacrossefootwear:feature/extension-attributes-autoloading?expand=1

**Comment by shochdoerfer** [comment]
@sprankhub if you people want to give this a try, install the dev-master version or wait until the release is done.

**Comment by sta1r** [comment]
Hi guys - thanks for adding this feature. 

We've been running 0.11.0 in a CI pipeline, and had seen previously added some errors relating to extension attributes to a baseline file. 

For example, analysing this class: https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/Ui/DataProvider/WebBehaviourTracking.php (level 2) we had:
```
------ --------------------------------------------------------------------- 
  Line   Ui/DataProvider/WebBehaviourTracking.php                             
 ------ --------------------------------------------------------------------- 
  91     Call to method setDdgSku() on an unknown class                       
         Magento\Catalog\Api\Data\ProductRenderExtensionInterface.            
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
``` 

Now, using 0.13.0, we get:
```
  91     Call to an undefined method                                            
         Magento\Catalog\Api\Data\ProductRenderExtensionInterface::setDdgSku().
```

Weirdly, although the pipeline complains, I can't reproduce the error in any of my local Magentos. 

So:
- Do you have any idea what might explain the discrepancy in behaviour between a brand new env and an existing one (stale cache of some kind?) 
- What's the best way of resolving the error itself?

**Comment by shochdoerfer** [comment]
@sta1r are you testing a stand-alone Magento module or a Magento application? I assume you try to test a stand-alone module. In that case, the current behavior is "ok" as the new extension attribute handling that was added in 0.13.0 only works for Magento applications. There's an additional PR open #174 which will fix this. Feel free to test #174, would love to get your feedback if it works for you.

Not exactly sure why it fails in CI but not on your local install. Are you sure that in both cases the same version of the extension is used? Ideally, you'd clean the phpstan cache in both CI and locally to see if this gets you any further.

**Comment by sta1r** [comment]
I'm testing a stand-alone module, so that now makes sense - thanks. I've cleared the result cache locally (CI is a fresh env each run) but the CI errors are still not reported. I've reverted to 0.11.0 in CI for now, and will re-check when 174 is released. I can't really test it I guess because I can't make the failures happen locally.

**Comment by shochdoerfer** [comment]
@sta1r we have just released 0.14.0 (compatible with PHPStan 1.2) and 0.15.0 (compatible with PHPStan 1.3). Both versions include the adaptions to make the extension attributes feature work for standalone Magento modules. If you run into problems, open a new issue.

**Comment by sta1r** [comment]
Just to add, relating to my comment above - I no longer get e.g. 
```
------ --------------------------------------------------------------------- 
  Line   Ui/DataProvider/WebBehaviourTracking.php                             
 ------ --------------------------------------------------------------------- 
  91     Call to method setDdgSku() on an unknown class                       
         Magento\Catalog\Api\Data\ProductRenderExtensionInterface.            
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
``` 

but I do still get:
```
------ ------------------------------------------------------------------------------------------
  Line   Ui/DataProvider/WebBehaviourTracking.php
 ------ ------------------------------------------------------------------------------------------
  87     PHPDoc tag @var for variable $extensionAttributes contains unknown class
         Magento\Catalog\Api\Data\ProductRenderExtension.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
  87     Variable $extensionAttributes in PHPDoc tag @var does not exist.
```

It appears from the comments posted earlier in this thread that this potentially ought to be resolved, but not sure. 

Again this is when testing [this class](https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/Ui/DataProvider/WebBehaviourTracking.php) using:
```
vendor/bin/phpstan analyse -l 2 app/code/Dotdigitalgroup/Email/Ui/DataProvider/WebBehaviourTracking.php
```

**Comment by shochdoerfer** [comment]
@sta1r the error shows up because the `Magento\Catalog\Api\Data\ProductRenderExtension` class does not exist. I could not find it in the Magento_Catalog module, so I guess the docblock comment is just wrong and would need to be fixed. Can you confirm that or am I missing something?

**Comment by sta1r** [comment]
`Magento\Catalog\Api\Data\ProductRenderExtension` is generated by the autoloader. It's as per the answer at https://magento.stackexchange.com/a/93384/142:
> All autogenerated classes are always based on another classes, in case of factory, source class name is calculated just by removing Factory suffix, it will be Magento\Quote\Api\Data\CartItemExtension. This class does not exist and autogeneration is invoked once again by autoloader, but this time for Extension class

I just figured that potentially that was something @mattwellss had addressed.

**Comment by shochdoerfer** [comment]
@sta1r my bad, thanks for pointing out. Looks like generating the classes for the "Extension" suffix is the missing link then. That does currently not work.
