### ISSUE TITLE
autoloader does not seem to be picked up when using the phpstan shim

### ISSUE THREAD

**Issue by kanduvisla** [bitExpert/phpstan-magento#14]
I'm trying to run phpstan in an isolated Magento module codebase, so I'm running into the case where factories etc. are not found.

I noticed the fix for this in `registration.php` for exactly this:

```
/**
 * Register given function as __autoload() implementation.
 *
 * @param callable $autoload_function
 * @param bool $throw
 * @param bool $prepend
 * @return bool
 */
function spl_autoload_register(callable $autoload_function, bool $throw = true, bool $prepend = false): bool
{
    // goal: convince PHPStan that classes generated by Magento - namely Factory & Proxy classes exists even when
    // they are not generated. When running PHPStan in a Magento application this is not a problem at all as Magento
    // will generate those files. When running PHPStan on a isolated Magento module codebase this is indeed a problem
    // as we don't have the Magento tooling in place to generate those classes.
    return \spl_autoload_register($autoload_function, $throw, $prepend) && Autoloader::register();
}
```

However, it does not seem to work. The `registration.php` file gets loaded, but the namespace-bound `spl_autoload_register` is not executed.

I am using the phpstan shim in my case. Could that be the cause of this problem?

**Comment by shochdoerfer** [comment]
HI @kanduvisla I would think the problem could be using the shim version. The readme of the GitHub repo sates that they are using a "prefixed" version, so I think the namespaces might be different.

Mind checking with the non-shim version?

**Comment by kanduvisla** [comment]
I'll check if I can get it to work with the non-shim version. In the meanwhile I did manage to find a fix for this issue when using the shim. I'm not sure if it's the best fix, but it might help others experiencing the same issue:

I've create a new file in the root of my module called `phpstan.php`:

```
<?php

declare(strict_types=1);

use bitExpert\PHPStan\Magento\Autoload\Autoloader;

// Since we're using the PHPStan Shim, we need to write a fix for the
// autoloader hack as defined by bitExpert/phpstan-magento:

Autoloader::register();
```

And in my `phpstan.neon` I've added the following line:

```
parameters:
    autoload_files:
        - phpstan.php
```

**Comment by kanduvisla** [comment]
I've tested with the non-shim version and I can confirm that works fine without the fix. So this is an issue caused by using the shim. I think this ticket can be closed now.

The only thing I can think of is to add an update to the README for known issues when using the shim (and perhaps suggest this fix?)

**Comment by shochdoerfer** [comment]
Mind providing a fix for the readme then? ;)
