### ISSUE TITLE
Upgrade to PHPStan 1.0

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/phpstan-magento#152]
PHPStan 1.0 got released today: https://phpstan.org/blog/phpstan-1-0-released

Check how "compatible" it is with the 0.x version we use and decide if it is worth upgrading. The downside of upgrading would be that the extension will be incompatible with the current Composer requirements in Magento 2.4 ` "phpstan/phpstan": "^0.12.77"`.

**Comment by shochdoerfer** [comment]
@sprankhub @hostep what are your thoughts on the PHPStan upgrade to version 1.0?

**Comment by shochdoerfer** [comment]
The 0.12.x versions won't get any more updates https://twitter.com/OndrejMirtes/status/1455083738564542467

**Comment by sprankhub** [comment]
If 0.x does not get any more updates, I think we should update to 1.0.

**Comment by hostep** [comment]
@shochdoerfer: I just tested the new major phpstan version out by hacking my composer dependencies like so:
```json
    "require-dev": {
        "bitexpert/phpstan-magento": "^0.9.0",
        "phpstan/phpstan": "1.0.2 as 0.12.99"
    },
```

This allowed me to install phpstan version 1.0.2 in combination with 0.9.0 of this module.

And executing phpstan works perfectly fine, so it looks like your module works without issues on version 1 of phpstan (not sure if my code covers all your features, so don't take this as your module is 100% compatible yet).
But in case it's discovered that this module works 100% fine with version 1.0 of phpstan, I would suggest to change the version constraints in your module to:

```json
    "phpstan/phpstan": "^0.12.23 || ^1.0"
```

This will allow people to keep using your module in a Magento 2 project, and also allow people that are using your module outside of a Magento 2 project to already upgrade to version 1.0 of phpstan.

**Comment by shochdoerfer** [comment]
@hostep thanks for your analysis. Very much appreciated. Good to know that things seem to work in both versions.

I feel there might be an issue with some dependencies as can be seen [here](https://github.com/bitExpert/phpstan-magento/runs/4101111627?check_suite_focus=true). I recall having read something similar somewhere in the PHPStan release notes or a tweet by Ondřej. I will investigate if this is fixable easily for both versions.

"Worst-case" approach would be to release a version 0.10 of the extension which would be compatible with 0.12 of PHPStan and a version 0.11 of the extension which is compatible with PHPStan 1.0 and maintain both for a while.

**Comment by hostep** [comment]
FYI: phpstan 1.x is also coming to Magento: https://github.com/magento/magento2/pull/34555 😉

**Comment by shochdoerfer** [comment]
@hostep stop doing MY job :P Had this on my todo list as well...

**Comment by shochdoerfer** [comment]
Quick update: Have to create a separate release for PHPStan 1.1 as a few internal changes broke the tests. That means we have a release 0.10 of the extension which supports PHPStan 0.12 and a release 0.11 of the extension to support PHPStan 1.1.
