### ISSUE TITLE
tmpDir should be relative to PHPStan configuration file path

### ISSUE THREAD

**Issue by mattwellss** [bitExpert/phpstan-magento#161]
According to PHPStan's documentation, the `tmpDir` parameter is calculated relative to the configuration file path: https://phpstan.org/config-reference#caching.

It's not 100% clear to me whether the parameter can be specified as an absolute path in addition to a relative path. Regardless, the current process for determining tmpDir uses the current working directory (https://github.com/bitExpert/phpstan-magento/blob/7ee91de2bb79c42e9d9b9561a5796ffcda63a81c/autoload.php#L49), which doesn't line up with PHPStan's docs.

I'd propose the following change (which supports only relative paths):
```php
$tmpDir = sys_get_temp_dir() . '/phpstan';
if (!empty($configFile)) {
    $neonConfig = Neon::decode(file_get_contents($configFile));
    if(is_array($neonConfig) && isset($neonConfig['parameters']) && isset($neonConfig['parameters']['tmpDir'])) {
        $tmpDir = realpath(dirname($configFile) . '/' . $neonConfig['parameters']['tmpDir']);
    }
}
```

If absolute paths are also allowed, we'll need to first check whether the configured path begins with a `/` (or golly, a drive letter for Windows?)

**Comment by shochdoerfer** [comment]
Thanks for spotting this. I don't remember why it was implemented that way. I feel I copied the logic from the PHPStan repo. But that's just a pure guess. Happy to change the logic to comply with PHPStan.

Did you encounter a specific bug with this?

**Comment by mattwellss** [comment]
In order to make "flushing" PHPStan's cache easier (now that it includes extension attributes interfaces, which change and require regeneration), I configured the cache to be local to the project. I'd noticed that the files generated by the phpstan-magento autoloader weren't showing up in that tmpDir, even though other PHPStan cache files were.

**Comment by shochdoerfer** [comment]
Mind sending a PR? :)
