### ISSUE TITLE
Installation Guide -- Should be .... :)

### ISSUE THREAD

**Issue by trunglv** [bitExpert/phpstan-magento#166]
Thank you for your great work here!
But I think, need to add more information in an installation guide.
For me: I have to install phpstan/extension-installer
Then have to change phpstan.neon:

parameters:
	bootstrapFiles:
		- vendor/bitexpert/phpstan-magento/autoload.php
includes:
	- vendor/phpstan/phpstan-strict-rules/rules.neon
	- vendor/bitexpert/phpstan-magento/extension.neon

It works for me. Thank you guys again a lot!

**Comment by shochdoerfer** [comment]
Thank you for opening this issue. Happy to extend the install section of the README.md file to make things a bit clearer.

When you install `phpstan/extension-installer` you should not need the includes directive as the extension-installer should figure out what the needed includes are. Could you check that, please?

Compared to what we have in the README.md file, I can't really spot a difference with your configuration. Except for the `vendor/phpstan/phpstan-strict-rules/rules.neon` include which you should not need unless you have installed the strict-rules extension.

**Comment by trunglv** [comment]
Hi Stefan,
*** "phpstan/extension-installer" automatically load a .neon file, if a composer.json of package has: ***
- "type": "phpstan-extension"
- "extra": {
    "phpstan": {
      "includes": [
        "extension.neon"
      ]
    }
  }.
*** Your extension has some works in a autoload file, so we need to define in PHPStan environment configure file.***
```
parameters:
	bootstrapFiles:
		- [...]/vendor/bitexpert/phpstan-magento/autoload.php
```
If you would add extension.neon somewhere else in  configurations, so it raises an error:
```
This file is included multiple times:
- /var/www/html/demo/vendor/bitexpert/phpstan-magento/extension.neon
```

**Comment by trunglv** [comment]
> Thank you for your great work here! But I think, need to add more information in an installation guide. For me: I have to install phpstan/extension-installer Then have to change phpstan.neon:
> 
> parameters: bootstrapFiles: - vendor/bitexpert/phpstan-magento/autoload.php includes: - vendor/phpstan/phpstan-strict-rules/rules.neon - vendor/bitexpert/phpstan-magento/extension.neon
> 
> It works for me. Thank you guys again a lot!

Sorry, for the confusing thing I wrote.

**Comment by shochdoerfer** [comment]
I will have look and see how to optimize the README.md file a bit. If you have any suggestions, let me know.
