### ISSUE TITLE
Improve extension attribute handling for standalone modules

### ISSUE THREAD

**Issue by mattwellss** [bitExpert/phpstan-magento#174]
As discussed in #162, I've tested extension attributes in a standalone module: https://github.com/lacrossefootwear/magento2-force-login/pull/1

The issue with standalone modules is here: https://github.com/bitExpert/phpstan-magento/blob/d4305053d8fb713de87bbd207c6bcb8264c272f7/src/bitExpert/PHPStan/Magento/Autoload/ExtensionInterfaceAutoloader.php#L177-L183

I did this to limit the list of extension attributes under consideration to only enabled modules, but the concept of enabled modules only exists when running a Magento app, not when developing a standalone module.

For standalone modules, I propose that we ignore whether a module is enabled or not, and grab `extension_attributes.xml` files from all _registered_ modules (which work great regardless of application or standalone).

In my testing, standalone modules work great with the extension attribute autoloader once this issue is resolved.

**Comment by shochdoerfer** [comment]
Makes sense and I am still surprised that my tests with the `magento/module-inventory-api` did seem to work fine. I manually disabled the extension interface autoloader and all the extension attribute errors popped up. After enabling the autoloader, the errors are gone. Not exactly sure what I did wrong, will try to replicate your tests.

How to solve this? I basically see 3 options:
 - come up with an automated solution to guess if we have to deal with a Magento application project or a Magento module project. Not sure how that could look like, though
 - add a configuration setting to "enable" the lookup via the component registrar
 - maybe we could register the project root as a fake module to make the component registrar believe a module is installed

**Comment by shochdoerfer** [comment]
I found out why my tests have been misleading: The `magento/module-inventory-api` uses the extension attribute interface but it does not define extension attributes via an `extension_attributes.xml` file.

I tested it with a different Magento module and can confirm your findings.

I am thinking to fix this with the 2nd solution proposed: By default, the PHPStan extension will scan for all `extension_attributes.xml` files in the project and take all of them into account. If the user wants to restrict this to only taking enabled modules into account, a configuration flag will be introduced to enable this feature.

**Comment by mattwellss** [comment]
I believe we can use the [`magentoRoot`](https://github.com/bitExpert/phpstan-magento/blob/9c97509376006ab0a2b152cc6ee4f325ebc26225/extension.neon#L5) parameter. Standalone modules do not employ this concept (no Magento application!), so we can make that parameter nullable and set the default to `null`.

If we use magento root, here's how the constructor would change:
```php
    public function __construct(Cache $cache, ?string $magentoRoot = null)
    {
        $this->cache = $cache;
        $this->componentRegistrar = new ComponentRegistrar();
        if ($magentoRoot !== null) {
            $this->moduleList = new ModuleList(
                new DeploymentConfig(
                    new DeploymentConfigReader(
                        new DirectoryList($magentoRoot),
                        new Filesystem\DriverPool(),
                        new ConfigFilePool()
                    )
                ),
                new Loader(
                    new ModuleDeclarationDom(),
                    new XmlParser(),
                    $this->componentRegistrar,
                    new FileDriver()
                )
            );
        }
    }
```

and then when finding module dirs we'd do this:
```php
        $moduleDirs = $this->componentRegistrar->getPaths(ComponentRegistrar::MODULE);

        // If magentoRoot was specified, only extract extension attributes from enabled modules
        if ($this->moduleList !== null) {
            $moduleDirs = array_filter(
                $moduleDirs,
                function ($moduleName) {
                    return $this->moduleList->has($moduleName);
                },
                ARRAY_FILTER_USE_KEY
            );
        }
```

**Comment by mattwellss** [comment]
Regardless of the method we choose to switch between standalone and application module discovery, what should the default be (`null` Magento root or cwd)?
