### ISSUE TITLE
Extend docs to cover Composer's 2.2 allow-plugins configuration

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/phpstan-magento#182]
Since in the docs the installation of `phpstan/extension-installer` is mentioned, we should cover the additional steps needed for Composer 2.2.0 which changes how Composer plugins are registered. See here for details: https://getcomposer.org/doc/06-config.md#allow-plugins

**Comment by torhoehn** [comment]
Should be solved now @shochdoerfer :)
