### ISSUE TITLE
Add autoloader and code generator to mimic ExtensionAttributesGenerator

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/phpstan-magento#189]
See the discussion here: https://github.com/bitExpert/phpstan-magento/issues/112#issuecomment-1009851754

Currently, only the extension attribute interfaces are generated but not the extension attribute classes.

**Comment by shochdoerfer** [comment]
@sta1r check the latest release 0.16.0 for a fix for this.

**Comment by sta1r** [comment]
@shochdoerfer Great stuff, the errors in that class I referenced have now been resolved. Thanks for chasing it down!
