### ISSUE TITLE
Add method description check

### ISSUE THREAD

**Issue by TimJnr** [bitExpert/phpstan-magento#222]
Hello.
I like your job and thank you.
Just a question, can I extend it adding extra rules? I want to check that method had some description. If yes, where I can do it, which classes can edit?

For example
    /**
     * Get products views from report_viewed_product_index table
     *
     * @param null $beginDate
     * @return array
     */
It is ok

    /**
     * @param null $beginDate
     * @return array
     */
It is not ok because we have only properties information and dont have description.

It can be great if this module will check has methods description or not.

**Comment by shochdoerfer** [comment]
Thank you for opening your first issue!

While I understand your need for such a rule, I feel the rule is a bit too generic for the very specific Magento use-case that this PHPStan extension covers. I am not sure if all of our users would agree with this rule and like it. From that point-of-view, I feel this is not the right place for this functionality.

However, that should not stop you from adding this rule to your project. You should be able to add the functionality in your Magento project or add it as a separate Composer package and make PHPStan aware of the new feature. I would assume that you need to create a custom rule implementation, see [here](https://phpstan.org/developing-extensions/rules#the-rule-interface) for more details. You would need to bind the rule to the method node type and then you should be able to get the Docblock comment for that method node in the processNode() node method. Then you need to parse it (that might be the tricky part) and then return an array of RuleError objects.

I hope this helps you to get started.
