### ISSUE TITLE
Cannot update to version 0.20.0 on Magento 2.4.4

### ISSUE THREAD

**Issue by BorisovskiP** [bitExpert/phpstan-magento#240]
Since Magento 2.4.4 has a version constraint on `phpstan/phpstan: ~1.2.0` its not possible to update `bitexpert/phpstan-magento` to version `0.20.0`.

Is it recommended to update the core Magento dependency to `~1.5.7` in order to use the new version of  `bitexpert/phpstan-magento` ?

**Comment by shochdoerfer** [comment]
Yes, you have to manually update the PHPStan to the matching version, see https://github.com/bitExpert/phpstan-magento#requirements

I tried to get the PHPStan dependency of Magento core updated to 1.5 before the 2.4.4 release, but sadly the merge was not done on time. So the same procedure with a manual update as before needs to be applied. That should change with the next Magento core release, as we have relaxed the dependency on a specific PHPStan version in Magento core a bit.

**Comment by BorisovskiP** [comment]
Thanks for the explanation.

**Comment by shochdoerfer** [comment]
@BorisovskiP just published version 0.21.0 of the extension which is compatible with PHPStan 1.6. Just in case you want to upgrade to the latest goodness ;)
