### ISSUE TITLE
DateTimeFactory Issue;

### ISSUE THREAD

**Issue by pvpcookie** [bitExpert/phpstan-magento#259]
Hi Bit Expert team, 

I believe there is an issue with PHP Stan regarding `DateTimeFactory`.

We believe the analyzer thinks the `DateTimeFactory`  is a generated one, and therefore should accept a single array arg, when in fact `Magento\Framework\Intl\DateTimeFactory` is an actual class shipped with the Magento framework.

Am i correct in this assumption or is there another solution opposed to ignoring the Error? 

See below ignore / Error message:
 ```
...  

 use Magento\Framework\Intl\DateTimeFactory;

...
 
       /**
         * Method Magento\Framework\Intl\DateTimeFactory::create() invoked
         * with 2 parameters, 0-1 required.
         *
         * @phpstan-ignore-next-line
         */
        $currentDate = $this->dateTimeFactory->create('now', new \DateTimeZone('UTC'));
...
 ```

**Comment by shochdoerfer** [comment]
Thanks for opening your first ticket in this repo. This is a duplicate #249, I think.

I assume you are using a PHPStan version > 1.7.4. If so, downgrade to 1.7.4 that should fix it for now. At least that is the gist of the ticket I mentioned above. I still need to prepare a demo to let Ondrej from PHPStan have a look.

**Comment by pvpcookie** [comment]
Hi, sorry i should've mentioned the version i'm using, we using `phpstan/phpstan 1.7.2`

**Comment by pvpcookie** [comment]
Using phpstan 1.7.4 worked. Thanks for your assistance

**Comment by shochdoerfer** [comment]
Awesome! Good to hear. Hopefully, we can get the PHPStan 1.8 upgrade done soonish and fix the issue in general.

**Comment by shochdoerfer** [comment]
@pvpcookie you can give the latest version 0.24.0 a try, it is compatible now with PHPStan 1.8 https://github.com/bitExpert/phpstan-magento/releases/tag/v0.24.0
