### ISSUE TITLE
Use Magento root for TestFrameworkAutoloader

### ISSUE THREAD

**Issue by evs-xsarus** [bitExpert/phpstan-magento#260]
I have all QA packages in a separate folder installed using composer. This to avoid version problems with the many Magento packages.

> /qa/
> /magento/

To run, for instance PHP Stan, I do:

```
cd magento
../qa/vendor/bin/phpstan analyse -c .phpstan.neon
```

This works fine, but I saw that the autoloader [TestFrameworkAutoloader](https://github.com/bitExpert/phpstan-magento/blob/master/src/bitExpert/PHPStan/Magento/Autoload/TestFrameworkAutoloader.php#L24) reads the vendor map in QA and not in Magento. I suggest using the $magentoRoot as you do in https://github.com/bitExpert/phpstan-magento/blob/master/src/bitExpert/PHPStan/Magento/Autoload/DataProvider/ClassLoaderProvider.php#L28

**Comment by shochdoerfer** [comment]
Thanks for opening your first issue. Fancy opening your first PR to fix this? ;)

Technically we don't support this setup anymore, in fact, what should not work when you do it like this is the extension attribute support. Since we rely on the Composer autoloader to check if a class or an interface exists, this will not work if you separate the phpstan/phpstan-magento installation from the Magento installation. If you don't care about extension attributes, the setup will work for you (but might break in future releases).

I would have loved to keep supporting this way but I could not find a way to reliably check if a class or interface exists.

**Comment by evs-xsarus** [comment]
@shochdoerfer if you could point to me the logic to check extension attributes, I'll have a look.

**Comment by evs-xsarus** [comment]
PS My .phpstan.neon is setup like:

```neon
parameters:
    level: 7
    fileExtensions:
        - php
    paths:
        - app/code/
        - app/design/

    reportUnmatchedIgnoredErrors: false

    checkMissingIterableValueType: false

    ignoreErrors:
        - '#^Class.*[a-z]Factory not found\.$#'
        - '#^Class.*[a-z]\\Proxy not found\.$#'
        - '#^Call to method create\(\) on an unknown class.*[a-z]Factory\.$#'
        - '#^Call to method create\(\) on an unknown class.*[a-z]\\Proxy\.$#'
        - '#^Parameter \$\w+ of method .*::.*\(\) has invalid (typehint )?type.*[a-z]Factory\.$#'
        - '#^Parameter \$\w+ of method .*::.*\(\) has invalid (typehint )?type.*[a-z]\\Proxy\.$#'
        - '#^Property .*::\$.* has unknown class.*[a-z]Factory as its type\.$#'
        - '#^Property .*::\$.* has unknown class.*[a-z]\\Proxy as its type\.$#'
        - '#^Return typehint of method .*::.*\(\) has invalid type.*[a-z]Factory\.$#'
        - '#^Return typehint of method .*::.*\(\) has invalid type.*[a-z]\\Proxy\.$#'
        - '#^Call to an undefined method.*[a-z]Interface::(get|set).*\(\)\.$#'
        - '#invalid type.*ExtensionInterface#'
        - '#should return.*ExtensionInterface.*but returns.*Magento\\Framework\\Api\\ExtensionAttributesInterface#'
        - '#Parameter \#1 \$extensionAttributes of method Magento\\Framework\\Api\\AbstractExtensibleObject::_setExtensionAttributes\(\) expects Magento\\Framework\\Api\\ExtensionAttributesInterface, .*ExtensionInterface given\.#'
        - '#Call to an undefined method Magento\\Framework\\GraphQl\\Query\\Resolver\\ContextInterface::getExtensionAttributes\(\)\.#'
        - '#Call to an undefined method object::getExtensionAttributes\(\).#'
        - '#unknown class [a-zA-Z0-9\\_]+ExtensionInterface#'
        - '#Class [a-zA-Z0-9\\_]+ExtensionInterface not found#'

    excludePaths:
        - %currentWorkingDirectory%/pub/errors/processor.php

includes:
    - .phpstan-baseline.neon
    - ../qa/vendor/bitexpert/phpstan-magento/extension.neon
```

Looking at this, I believe I'm ignoring the extension attributes anyway.

**Comment by shochdoerfer** [comment]
@evs-xsarus correct, you are ignoring the errors anyways.

**Comment by shochdoerfer** [comment]
@evs-xsarus I prepared a PR, mind giving it a try? https://github.com/bitExpert/phpstan-magento/pull/267

**Comment by evs-xsarus** [comment]
Looking at the code, I believe it should work. My debugger doesn't stop in the TestFramewordAutoloader with PHPStan 1.8.x. Probably due to https://github.com/bitExpert/phpstan-magento/issues/249 .

**Comment by shochdoerfer** [comment]
dev-master version seems to work for me. Will release a new version soon, if you run into problems open a new issue.

**Comment by shochdoerfer** [comment]
Here you go: https://github.com/bitExpert/phpstan-magento/releases/tag/v0.24.0
