### ISSUE TITLE
Project config file at path app/code/Vendor/Module does not exist.

### ISSUE THREAD

**Issue by MagePsycho** [bitExpert/phpstan-magento#262]
I have installed the `phpstan-magento` on
```
composer require phpstan/phpstan ~1.7.2
composer require --dev phpstan/extension-installer
```

After running the `phpstan` command to analyze the code
```
vendor/bin/phpstan analyse -c app/code/Vendor/Module --level 0
```
is giving error  
> Project config file at path app/code/Vendor/Module does not exist.

**Comment by BrentRobert** [comment]
@MagePsycho do you have a module called 'Vendor_Module'? The directory you're pointing it to probably does not exist, it needs to be pointed to a valid module.

**Comment by shochdoerfer** [comment]
@MagePsycho maybe you can find some guidance in this repo https://github.com/hivecommerce/magerun2-list-api-endpoints

**Comment by shochdoerfer** [comment]
IIRC correctly our conversation on LinkedIn the problem is solved. If you run into further issues, feel free to open another issue. Thanks for giving this extension a try! Hopefully, you'll find it useful.
