### ISSUE TITLE
private string $magentoRoot; not work in PHP 7.2

### ISSUE THREAD

**Issue by hugofintecture** [bitExpert/phpstan-magento#271]
Hello!

I've this error on CI:

```
Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /builds/qkSMQzG3/0/applications/integration-magento2/magento2.3-2.4/vendor/bitexpert/phpstan-magento/src/bitExpert/PHPStan/Magento/Autoload/TestFrameworkAutoloader.php on line 21
```

 Typed properties have been introduced in PHP 7.4 I think but this package is marked as compatible from PHP 7.2.

Thanks in advance :)

**Comment by shochdoerfer** [comment]
Good catch! Somehow I had in mind that Magento 2.3.0 would only support 7.4, but it does support 7.2 (and heck even 7.1).

**Comment by hugofintecture** [comment]
Thanks for your reactivity 🙏

**Comment by shochdoerfer** [comment]
For now, you can use the dev-master version, not sure yet when I will create the next release. Want to fix a few more things but don't know yet when to find the time.

**Comment by hugofintecture** [comment]
Yes of course, thanks for your time!
