### ISSUE TITLE
Compatibility with PHPstan 1.10.x

### ISSUE THREAD

**Issue by hostep** [bitExpert/phpstan-magento#294]
Hi there

PHPstan 1.10.x versions are being released since a few days: https://github.com/phpstan/phpstan/releases

However, this module has a pretty strict constraint on it: `~1.9.2` which prevents us from upgrading to them.

Can't we open up the constraint a bit more, so that newer versions of phpstan (which are supposed to be backwards compatible) can also be installed, so maybe: `^1.9.2` ?

Thanks!

**Comment by shochdoerfer** [comment]
I added the strict constraint last year on purpose. I added it after the issues with the autoloader changes in PHPStan core happened which broke this extension.

In other news: Will be working on updating the dependencies in the next few days. Be a bit patient :)

**Comment by hostep** [comment]
Okay, perfect, no worries, take your time 😄

**Comment by shochdoerfer** [comment]
Here you go: https://github.com/bitExpert/phpstan-magento/releases/tag/v0.29.0

Let me know if this breaks anything :)

**Comment by hostep** [comment]
Many thanks! Just tested it out quickly and seems to work fine on some small modules.
