### ISSUE TITLE
PHPStan Does Not Find \Magento\TestFramework\Helper\Bootstrap

### ISSUE THREAD

**Issue by sprankhub** [bitExpert/phpstan-magento#31]
### Preconditions
1. Magento 2.3.4
2. PHP 7.2
3. `bitexpert/phpstan-magento` 0.1.0

### Steps to reproduce
1. Create an example integration test in your module, e.g. `\Company\Module\Test\Integration\ExampleTest`:

        <?php
        
        declare(strict_types=1);
        
        namespace Company\Module\Test\Integration;
        
        use Magento\TestFramework\Helper\Bootstrap;
        use PHPUnit\Framework\TestCase;
        
        class ExampleTest extends TestCase
        {
            protected function setUp(): void
            {
                Bootstrap::getObjectManager();
            }
        }

2. Run `vendor/bin/phpstan analyze --level=8 src/Company/Module/Test/Integration`.

### Expected result
1. No issues are found.

### Actual result
1. One issue is found:

        Call to static method getObjectManager() on an unknown class Magento\TestFramework\Helper\Bootstrap

### Workaround
Ignore the error in your `phpstan.neon`:

    ignoreErrors:
        - '#Call to static method getObjectManager\(\) on an unknown class Magento\\TestFramework\\Helper\\Bootstrap.#'

The same issue occurs when you try to use the alternative `\Magento\Framework\App\ObjectManager::getInstance`, so this can unfortunately not be used as a workaround.

### Idea
Do we need to add another custom autoloader for `Magento\TestFramework`?

**Comment by shochdoerfer** [comment]
Looks like the different testing extensions come with their own autoloading logic. We need to load/include them somehow in this extension. I will have a look at that. Thanks for bringing up this issue.

**Comment by shochdoerfer** [comment]
See `dev/tests/integration/framework/autoload.php` or `dev/tests/api-functional/framework/autoload.php` for the implementation.

**Comment by shochdoerfer** [comment]
@sprankhub could you please give #32 a try? Looks good to me but would love to hear your feedback before merging :)

**Comment by sprankhub** [comment]
I can confirm that your PR fixes the issue. Thanks a lot, @shochdoerfer!

**Comment by shochdoerfer** [comment]
Will create a new release soonish!
