### ISSUE TITLE
Add support for phpstan 1.12

### ISSUE THREAD

**Issue by hostep** [bitExpert/phpstan-magento#325]
Hiya!

Would be nice if the module can be released with support for phpstan 1.12, see:
- https://github.com/phpstan/phpstan/releases
- https://phpstan.org/blog/phpstan-1-12-road-to-phpstan-2-0

It sounds like this is the last minor version release line before they'll release 2.0

Maybe we can consider switching again to `^1.11.1` constraint instead of `~1.11.1` for phpstan, as it's supposed to be backwards compatible?

Already tried with phpstan version 1.12.0 on 4 small modules and 1 semi larger project, no issues found.

**Comment by shochdoerfer** [comment]
Thanks for testing :)

Will try to merge #326 soonish.

**Comment by shochdoerfer** [comment]
@hostep here you go https://github.com/bitExpert/phpstan-magento/releases/tag/v0.32.0
