### ISSUE TITLE
Replace custom autoloaders with Magento's implementation

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/phpstan-magento#34]
To investigate: Could we use the `Magento\Framework\TestFramework\Unit\Autoloader` implementations to generate the code and autoload it instead of our own custom logic? Or maybe reimplement `Magento\Framework\Code\Generator\Autoloader` to get rid of the ObjectManager magic.

**Comment by makao** [comment]
For Magento projects you can use 
```
parameters:
    bootstrapFiles:
        - dev/tests/static/framework/Magento/PhpStan/autoload.php
```
[Reference - Magento](https://github.com/magento/magento2/blob/2.4-develop/dev/tests/static/framework/Magento/PhpStan/autoload.php)
[Reference - PHPStan](https://phpstan.org/user-guide/discovering-symbols#custom-autoloader)

For developing custom modules you need to create (copy) autoloader in your module to be able to run PHPStan without installing whole Magento.

**Comment by shochdoerfer** [comment]
Thanks for pointing out. That does make sense of course.

I am still undecided about how to drive this project forward as this project depends on a newer version of PHPStan compared to what Magento 2.4.0 depends on as outlined in #42.

**Comment by makao** [comment]
I think you shouldn't care which PHPStan version Magento is using as probably you don't want to test vendor code with it. I've used your package for testing project code located in app/code, we had used higher level than Magento is using and we were even patching some Magento core code to fix incorrect annotations.

When you create Magento project you can simply update your dev dependencies. Also every 3rd party module should test code itself, to sum up I think you should go with latest PHPStan, not latest used by Magento.

**Comment by shochdoerfer** [comment]
I just realized that we actually can't rely on Magento's autoloader for module projects because the autoloader is not shipped in one of Magento's Composer dependencies. Guess we'll have to keep our own solution for now.
