### ISSUE TITLE
Deprecated Config Option autoload_files

### ISSUE THREAD

**Issue by sprankhub** [bitExpert/phpstan-magento#40]
When using  the current `dev-master` and using the recommended configuration from the `README.md`, there is a deprecation warning when running PHPStan:

    Note: Using configuration file /var/www/project/phpstan.neon.
    ⚠️  You're using a deprecated config option autoload_files. ⚠️️

    You might not need it anymore - try removing it from your
    configuration file and run PHPStan again.

    If the analysis fails, there are now two distinct options
    to choose from to replace autoload_files:
    1) scanFiles - PHPStan will scan those for classes and functions
       definitions. PHPStan will not execute those files.
    2) bootstrapFiles - PHPStan will execute these files to prepare
       the PHP runtime environment for the analysis.

    Read more about this in PHPStan's documentation:
    https://phpstan.org/user-guide/discovering-symbols

Removing the option altogether does not work for me, because I get the error "Call to static method `getObjectManager()` on an unknown class `Magento\TestFramework\Helper\Bootstrap`" again in this case.

**Comment by shochdoerfer** [comment]
Thanks for letting us know. Seems like the `autoload_files` option got deprecated with PHPStan 0.12.26. Removing `autoload_files` won't work as the file contains the logic to register the custom autoloaders.

Could you try to rename `autoload_files` to `bootstrapFiles` and see if things are working again?

**Comment by sprankhub** [comment]
This indeed seems to work :)

**Comment by shochdoerfer** [comment]
Ok, that was easy then ;) Had the impression that both parameters worked differently when I read the docs back then. Good to know that it is just a "minor" change.
