### ISSUE TITLE
Feature request: Add objectManager type hints for Unit tests

### ISSUE THREAD

**Issue by oneserv-heuser** [bitExpert/phpstan-magento#45]
Hi!
You already have the nice feature with the [ObjectManager type hints](https://github.com/bitExpert/phpstan-magento#objectmanager-type-hints).
But magento also provides another [ObjectManager for unit tests](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/test/test_object-mgr.html). The problem is that  the class [ObjectManagerDynamicReturnTypeExtension](https://github.com/bitExpert/phpstan-magento/blob/master/src/bitExpert/PHPStan/Magento/Type/ObjectManagerDynamicReturnTypeExtension.php) just provides support for the default magento objectmanager as seen [here](https://github.com/bitExpert/phpstan-magento/blob/b7d527a752e0ca30466ebabbbade93b3d3321f1a/src/bitExpert/PHPStan/Magento/Type/ObjectManagerDynamicReturnTypeExtension.php#L32).

So now when assigning the return value of the getObject() function to an class property with phpDoc the following phpstan error occurs: `Property Oneserv\TestFramework\Test\Unit\Test::$testClass (Oneserv\TestFramework\Test\Unit\TestClass) does not accept object` as the return type of the function is just object.

Here is a minium example:
````PHP
<?php

declare(strict_types=1);

namespace Oneserv\TestFramework\Test\Unit;

/**
 * Class Test
 */
class Test extends AbstractTestCase
{
    /** @var TestClass */
    protected $testClass;

    /**
     * @inheritDoc
     */
    protected function setUp(): void
    {
        parent::setUp();

        $this->testClass = $this->objectManager->getObject(TestClass::class);
    }
}

````

I would love having this feature to avoid ignoring the error!

**Comment by shochdoerfer** [comment]
@sprankhub did you also run into this?

Of course we have to fix this ;) Need to check how. Thanks for opening your first issue @oneserv-heuser here!

**Comment by sprankhub** [comment]
I did not encounter this, because we usually do not write unit tests :-)

**Comment by shochdoerfer** [comment]
@oneserv-heuser quick update on this issue: Still working on it, having some issues with the type system of PHPStan.

**Comment by shochdoerfer** [comment]
Hey @oneserv-heuser I uploaded a first test version in #47. Mind checking this against your repo(s)? My very limited test looked good, would be lovely to get some real world feedback before merging :)

**Comment by oneserv-heuser** [comment]
@shochdoerfer Tested and it works like a charm! Thanks a lot!

**Comment by shochdoerfer** [comment]
I'll add a bit more error checks soonish (e.g. make sure that you can only pass `\Magento\Framework\Data\Collection` instances to the getCollectionMock() method and then merge & release.

**Comment by oneserv-heuser** [comment]
@shochdoerfer How does it look? I am waiting impatiently for the release 😄

**Comment by shochdoerfer** [comment]
@oneserv-heuser sorry for letting you down, the last weeks have once again been too busy to get this going. My plan is to release a new version this week. It may not include the extended error checks for now, that depends a bit on how much I can find to work on this.

**Comment by shochdoerfer** [comment]
@oneserv-heuser quick update: Still on it, sorry. I ran into a bunch of problems that I need to solve first before I can merge the changes.

**Comment by shochdoerfer** [comment]
@oneserv-heuser just pushed the latest changes to the PR. Mind testing the branch against your codebase? Had to make a few minor adjustments and added a rule to deject wrong classes passed to the getCollectionMock() method. Seems to work in my simplified test environment. Would now need some real-world insights :)

**Comment by oneserv-heuser** [comment]
@shochdoerfer I just can repeat myself, works like a charm 👍🏻 
But now it also makes 2 @phpstan-ignore-next-line redundant in tests, so it's even better

**Comment by shochdoerfer** [comment]
Here we go: https://github.com/bitExpert/phpstan-magento/releases/tag/v0.5.0
