### ISSUE TITLE
Set magic method for DataObject requires argument `$key` of type `array|string`

### ISSUE THREAD

**Issue by paulvandermeijs** [bitExpert/phpstan-magento#51]
Example:

```php
<?php

use Magento\Framework\DataObject;

$myObject = new DataObject();

$myObject->setMyMagic(1);
```

Generates:

```
------ -------------------------------------------------------------------------------- 
  Line   test.php                                                                        
 ------ -------------------------------------------------------------------------------- 
  7      Parameter #1 $key of method Magento\Framework\DataObject::setMyMagic() expects  
         array|string, int given.                                                        
 ------ --------------------------------------------------------------------------------
```

I believe this is cause by this definition:

https://github.com/bitExpert/phpstan-magento/blob/22b23622313605ee95d15d8ac01f698290ece9a0/src/bitExpert/PHPStan/Magento/Reflection/AbstractMagicMethodReflectionExtension.php#L96-L115

Which I believe should be just a single parameter with a mixed type; this seems to describe the signature of `DataObject::setData()`. I'm not familiar with the inner workings of PHPStan though so I'm not sure about any additional impact of this change.

**Comment by shochdoerfer** [comment]
Thanks for using this PHPStan extension and thanks for your first bug report. I will have a look. Indeed it looks like the definition is messed up, need to check why.

**Comment by shochdoerfer** [comment]
@paulvandermeijs here we go https://github.com/bitExpert/phpstan-magento/releases/tag/v0.6.0
